[package]
name = "santozstudios/restaurentsim"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
roact = "roblox/roact@1.4.4"
Signal = "sleitnick/signal@^1"
Promise = "evaera/promise@3.1.0"
Janitor = "howmanysmall/janitor@^1.17.0"
flipper = "reselim/flipper@2.0.0"
viewportmodel = "bubshurb/viewportmodel@1.0.0"
zoneplus = "mattschrubb/zoneplus@3.2.0"