name: Deploy Prod

on:
    push:
        tags:
            - v*

jobs:
    lint:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - uses: Roblox/setup-foreman@v1
          name: Install Foreman
          with:
                version: "^1.0.0"
                token: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Build Place
          run: rojo build -o build.rbxlx

        - name: Publish Prod
          shell: bash
          env:
            UID: 6448018291
            PID: 84645288604594
            API_KEY: ${{ secrets.PUBLISHING_API_KEY }}
            FILE: build.rbxlx
          run: rbxcloud experience publish -a "$API_KEY" -u "$UID" -p "$PID" -t published -f "$FILE"