name: Deploy Prod

on:
    push:
        tags:
            - v*

jobs:
    lint:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - uses: ok-nick/setup-aftman@v0.3.0
          name: Install aftman
          with:
              token: ${{ SECRETS.GITHUB_TOKEN }}
        
        - name: Build Place
          run: rojo build -o build.rbxlx

        - name: Publish Prod
          shell: bash
          env:
            UID: 6534218046
            PID: 124183201707327
            API_KEY: ${{ secrets.PUBLISHING_API_KEY }}
            FILE: build.rbxlx
          run: rbxcloud experience publish -a "$API_KEY" -u "$UID" -p "$PID" -t published -f "$FILE"